# Generated by Django 3.2.6 on 2021-08-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210822_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_in_stock',
            field=models.IntegerField(default=0),
        ),
    ]
